In [1]:
import numpy as np
import pandas as pd

Checando NaN e inf

In [8]:
np.isnan(np.nan)

True

In [9]:
np.isinf(np.inf)

True

In [10]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [11]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [12]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [13]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

Filtrando...

In [7]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [3]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [6]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [4]:
a[np.isfinite(a)].sum()

10.0

In [5]:
a[np.isfinite(a)].mean()

2.5